In [15]:
## initially Lets import numpy

import numpy as np

In [16]:
lst=[1,2,3,4,5]

arr=np.array(lst)

In [17]:
print(arr)

[1 2 3 4 5]


In [18]:
type(arr)

numpy.ndarray

In [19]:
## Multinested array
lst1=[1,2,3,4,5]
lst2=[2,3,4,5,6]
lst3=[9,7,6,8,9]

arr=np.array([lst1,lst2,lst3])

In [20]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [21]:
type(arr)

numpy.ndarray

In [22]:
## check the shape of the array

arr.shape

(3, 5)

In [23]:
z=np.zeros([5,3])
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.ones([5,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
np.diag([14,15,16,17])

array([[14,  0,  0,  0],
       [ 0, 15,  0,  0],
       [ 0,  0, 16,  0],
       [ 0,  0,  0, 17]])

### Indexing 

In [26]:
## Accessing the array elements

arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [27]:
arr[0,3]

4

In [28]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [29]:
arr[1:,:2]

array([[2, 3],
       [9, 7]])

In [30]:
arr[:,3:]

array([[4, 5],
       [5, 6],
       [8, 9]])

In [31]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [32]:
arr[3:]=100

In [33]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [34]:
### Some conditions very useful in Exploratory Data Analysis 

val=2

arr[arr<3]

array([1, 2, 2])

In [35]:
## Create arrays and reshape

np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [36]:
arr1=np.arange(0,10).reshape(2,5)

In [37]:
arr2=np.arange(0,10).reshape(2,5)

In [38]:
arr1*arr2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [39]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [40]:
## random distribution
np.random.rand(3,3)

array([[0.05236046, 0.25708569, 0.35235857],
       [0.29698603, 0.68759781, 0.62323826],
       [0.8352787 , 0.31122401, 0.53059059]])

In [41]:
arr_ex=np.random.randn(4,4)

In [42]:
arr_ex

array([[ 2.17181372, -0.28507156, -0.70323855, -1.2434018 ],
       [-0.22496258,  0.4780087 ,  1.9611212 ,  0.44913039],
       [ 0.09511922,  0.24314122,  0.96540337,  1.44124198],
       [ 0.28187904, -2.52469621, -0.25814954, -0.8400047 ]])

In [45]:
np.random.randint(0,100,8).reshape(4,2)

array([[15, 81],
       [33, 56],
       [79, 43],
       [31, 73]])

In [46]:
np.random.random_sample((1,5))

array([[0.0081869 , 0.21087755, 0.051294  , 0.23186306, 0.51648009]])

# REFERENCE LINKS


# https://www.listendata.com/2017/12/numpy-tutorial.html